function opcodelist = dng_opcodelist_template(M)

% 
% At the start of opcode list, there is a 32-bit unsigned integer count, which contains the number
% of opcodes in the list. This is followed by the data for each opcode.
% Each opcode starts with a 32-bit unsigned integer, which contains the opcode ID. The opcode
% ID identifies the specific opcode. Documentation for each supported opcode ID in provided
% later in this chapter.

% Next is a 32-bit unsigned integer, which contains the DNG specification version in which the
% opcode ID was defined. It is expected that new opcode IDs will be defined in future DNG
% specification versions. A DNG reader should never attempt to process an opcode with a
% version higher than DNG specification it was written to support.

% Next is a 32-bit unsigned integer, which contains various flag bits. There are two defined flag
% bits. If bit 0 (the least significant bit) is set to 1, the opcode is considered optional, and the
% DNG reader may decide to not apply this opcode if it wishes, or it does not understand the
% opcode ID. If bit 1 (the second to least significant bit) is set to 1, the opcode can be skipped
% when doing “preview quality” processing, and only needs to be applied when doing “full
% quality” processing.

% Next is a 32-bit unsigned integer, containing the number of bytes in a variable size parameter
% area for the opcode. The format of this variable size parameter area is dependent on the
% specific opcode ID, and is documented later in this chapter, along with each supported opcode
% ID.

% lscTableSize = 32 * 32 * 4;% lsc_h x lsc_v * sizeof(float)
% opcodelist.NumberOfOpcodeGainMaps = 4;
%opcodelist.mapplanes = 1;
%opcodelist.mapsize = lscTableSize;


%blue
opcodelist = {...
  struct('description','NumberOfOpcodeGainMaps','type',4,'count',1,'values',[4]),...
  struct('description','OpcodeheaderB.OpcodeIDGainMap','type',4,'count',1,'values',[9]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeSpecVer','type',4,'count',1,'values',[16973824]),...  
  struct('description','opcodelist.OpcodeheaderB.OpcodeFlags','type',4,'count',1,'values',[0]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeIDGainMapSize','type',4,'count',1,'values',[76+4*32*32]),...
  struct('description','opcodelist.GainMapB.Top','type',4,'count',1,'values',[1]),...  
  struct('description','opcodelist.GainMapB.Left','type',4,'count',1,'values',[0]),...    
  struct('description','opcodelist.GainMapB.Right','type',4,'count',1,'values',M.height),...   
  struct('description','opcodelist.GainMapB.Bottom','type',4,'count',1,'values',M.width),...     
  struct('description','opcodelist.GainMapB.Plane','type',4,'count',1,'values',[0]),...       
  struct('description','opcodelist.GainMapB.Planes','type',4,'count',1,'values',[1]),...       
  struct('description','opcodelist.GainMapB.RowPitch','type',4,'count',1,'values',[2]),...       
  struct('description','opcodelist.GainMapB.ColPitch','type',4,'count',1,'values',[2]),...  
  struct('description','opcodelist.GainMapB.MapPointsH','type',4,'count',1,'values',[32]),...
  struct('description','opcodelist.GainMapB.MapPointsV','type',4,'count',1,'values',[32]),...  
  struct('description','opcodelist.GainMapB.MapSpacingH','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapSpacingV','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapOriginH','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapOriginV','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapPlanes','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainB','type',11,'count',32*32,'values',M.lensshading_b),...    
  struct('description','OpcodeheaderB.OpcodeIDGainMap','type',4,'count',1,'values',[9]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeSpecVer','type',4,'count',1,'values',[16973824]),...  
  struct('description','opcodelist.OpcodeheaderB.OpcodeFlags','type',4,'count',1,'values',[0]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeIDGainMapSize','type',4,'count',1,'values',[76+4*32*32]),...
  struct('description','opcodelist.GainMapB.Top','type',4,'count',1,'values',[1]),...  
  struct('description','opcodelist.GainMapB.Left','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainMapB.Right','type',4,'count',1,'values',M.height),...   
  struct('description','opcodelist.GainMapB.Bottom','type',4,'count',1,'values',M.width),...     
  struct('description','opcodelist.GainMapB.Plane','type',4,'count',1,'values',[0]),...       
  struct('description','opcodelist.GainMapB.Planes','type',4,'count',1,'values',[1]),...       
  struct('description','opcodelist.GainMapB.RowPitch','type',4,'count',1,'values',[2]),...       
  struct('description','opcodelist.GainMapB.ColPitch','type',4,'count',1,'values',[2]),...  
  struct('description','opcodelist.GainMapB.MapPointsH','type',4,'count',1,'values',[32]),...
  struct('description','opcodelist.GainMapB.MapPointsV','type',4,'count',1,'values',[32]),...  
  struct('description','opcodelist.GainMapB.MapSpacingH','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapSpacingV','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapOriginH','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapOriginV','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapPlanes','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainB','type',11,'count',32*32,'values',M.lensshading_g),...     
  struct('description','OpcodeheaderB.OpcodeIDGainMap','type',4,'count',1,'values',[9]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeSpecVer','type',4,'count',1,'values',[16973824]),...  
  struct('description','opcodelist.OpcodeheaderB.OpcodeFlags','type',4,'count',1,'values',[0]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeIDGainMapSize','type',4,'count',1,'values',[76+4*32*32]),...
  struct('description','opcodelist.GainMapB.Top','type',4,'count',1,'values',[0]),...  
  struct('description','opcodelist.GainMapB.Left','type',4,'count',1,'values',[0]),...    
  struct('description','opcodelist.GainMapB.Right','type',4,'count',1,'values',M.height),...   
  struct('description','opcodelist.GainMapB.Bottom','type',4,'count',1,'values',M.width),...     
  struct('description','opcodelist.GainMapB.Plane','type',4,'count',1,'values',[0]),...       
  struct('description','opcodelist.GainMapB.Planes','type',4,'count',1,'values',[1]),...       
  struct('description','opcodelist.GainMapB.RowPitch','type',4,'count',1,'values',[2]),...       
  struct('description','opcodelist.GainMapB.ColPitch','type',4,'count',1,'values',[2]),...  
  struct('description','opcodelist.GainMapB.MapPointsH','type',4,'count',1,'values',[32]),...
  struct('description','opcodelist.GainMapB.MapPointsV','type',4,'count',1,'values',[32]),...  
  struct('description','opcodelist.GainMapB.MapSpacingH','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapSpacingV','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapOriginH','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapOriginV','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapPlanes','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainB','type',11,'count',32*32,'values',M.lensshading_g),...      
  struct('description','OpcodeheaderB.OpcodeIDGainMap','type',4,'count',1,'values',[9]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeSpecVer','type',4,'count',1,'values',[16973824]),...  
  struct('description','opcodelist.OpcodeheaderB.OpcodeFlags','type',4,'count',1,'values',[0]),...
  struct('description','opcodelist.OpcodeheaderB.OpcodeIDGainMapSize','type',4,'count',1,'values',[76+4*32*32]),...
  struct('description','opcodelist.GainMapB.Top','type',4,'count',1,'values',[0]),...  
  struct('description','opcodelist.GainMapB.Left','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainMapB.Right','type',4,'count',1,'values',M.height),...   
  struct('description','opcodelist.GainMapB.Bottom','type',4,'count',1,'values',M.width),...     
  struct('description','opcodelist.GainMapB.Plane','type',4,'count',1,'values',[0]),...       
  struct('description','opcodelist.GainMapB.Planes','type',4,'count',1,'values',[1]),...       
  struct('description','opcodelist.GainMapB.RowPitch','type',4,'count',1,'values',[2]),...       
  struct('description','opcodelist.GainMapB.ColPitch','type',4,'count',1,'values',[2]),...  
  struct('description','opcodelist.GainMapB.MapPointsH','type',4,'count',1,'values',[32]),...
  struct('description','opcodelist.GainMapB.MapPointsV','type',4,'count',1,'values',[32]),...  
  struct('description','opcodelist.GainMapB.MapSpacingH','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapSpacingV','type',12,'count',1,'values',[1.0/32]),...    
  struct('description','opcodelist.GainMapB.MapOriginH','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapOriginV','type',12,'count',1,'values',[0.0]),...    
  struct('description','opcodelist.GainMapB.MapPlanes','type',4,'count',1,'values',[1]),...    
  struct('description','opcodelist.GainB','type',11,'count',32*32,'values',M.lensshading_r)};    
  
